stages: [lint, test, build]

phpstan:
  stage: lint
  image: php:8.2-cli
  script:
    - curl -Ls https://github.com/phpstan/phpstan/releases/latest/download/phpstan.phar -o phpstan
    - php phpstan --version
    - php phpstan analyse

phpunit:
  stage: test
  image: php:8.2-cli
  script:
    - curl -Ls https://phar.phpunit.de/phpunit-10.phar -o phpunit
    - php phpunit --version
    - php phpunit

package:
  stage: build
  image: alpine:3.19
  script:
    - zip -r build.zip plugins shared README.md ROADMAP.md ADRs -x "**/vendor/*"
  artifacts:
    paths: [build.zip]
