### Produkt-Listing
POST https://api.example.local/store-api/product-listing/acme-category
accept: application/json
sw-access-key: [[SALES-CHANNEL-KEY]]
content-type: application/json

{
  "includes": {
    "product": ["id", "name", "price"]
  }
}

### Warenkorb erstellen
POST https://api.example.local/store-api/checkout/cart
accept: application/json
sw-access-key: [[SALES-CHANNEL-KEY]]
content-type: application/json

{
  "name": "acme-headless-cart"
}

### Warenkorb-Position hinzufügen
POST https://api.example.local/store-api/checkout/cart/line-item
accept: application/json
sw-access-key: [[SALES-CHANNEL-KEY]]
content-type: application/json
sw-context-token: [[CONTEXT-TOKEN]]

{
  "type": "product",
  "referencedId": "[[PRODUCT-ID]]",
  "quantity": 1
}

### Checkout vorbereiten
POST https://api.example.local/store-api/checkout/order
accept: application/json
sw-access-key: [[SALES-CHANNEL-KEY]]
content-type: application/json
sw-context-token: [[CONTEXT-TOKEN]]

{
  "customer": {
    "email": "kundenmail@example.local",
    "password": "[[OPTIONAL]]"
  },
  "paymentMethodId": "[[PAYMENT-ID]]",
  "shippingMethodId": "[[SHIPPING-ID]]",
  "billingAddress": {
    "salutationId": "[[SALUTATION-ID]]",
    "firstName": "Max",
    "lastName": "Mustermann",
    "street": "Musterweg 1",
    "zipcode": "12345",
    "city": "Musterstadt",
    "countryId": "[[COUNTRY-ID]]"
  }
}
